services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP cho các ứng dụng kết nối
      - "15672:15672"  # web management UI
    restart: unless-stopped